f = open('data.txt', 'r', encoding="utf-8")
text = f.read()
print(text +"+" )

f.close()
f1 = open('data1.txt', 'r', encoding="utf-8")
text1 = f1.read()
print(text1)
f1.close()
f2 = open('data2.txt', 'r', encoding="utf-8")
text2 = f2.read()
print("=")
print(text2)
f2.close()
